name: "Sync Paperpile to Notion"

on:
  workflow_dispatch: { }
  push:
    paths:
      - "**.bib"

jobs:
  sync-to-notion:
    name: "Sync Paperpile to Notion"

    runs-on: "ubuntu-latest"

    concurrency:
      group: "paperpile-sync"
      cancel-in-progress: true

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Run `paperpile-notion` sync"
        uses: "jmuchovej/paperpile-notion@latest"
        with:
          references: "references.bib"
          token: "${{ secrets.NOTION_INTEGRATION_TOKEN }}"
